upgrade to version 9.4

diff --git a/pgadmin4-slackbuild/pgadmin4.SlackBuild b/pgadmin4-slackbuild/pgadmin4.SlackBuild
--- a/pgadmin4-slackbuild/pgadmin4.SlackBuild
+++ b/pgadmin4-slackbuild/pgadmin4.SlackBuild
@@ -1,10 +1,7 @@
 #!/bin/bash
 
-# Updated for pgAdmin4 version 8.9
-# Date: July 7/2024
-
-# Note: this requires nodejs version : ^18.18.0 || ^20.9.0 || >= 21.1.0
-# to build the documentations; version used was == 21.1.0
+# Updated for pgAdmin4 version 9.4
+# Date: June/11/2025
 
 # Slackware build script for pgadmin4
 # Copyright 2019 Jeremy Hansen jebrhansen+SBo -at- gmail.com
@@ -31,7 +28,7 @@
 
 CWD=$(pwd)
 PRGNAME=pgadmin4
-VERSION="8.9"
+VERSION="9.4"
 BUILD=${BUILD:-1}
 TAG=${TAG:-_wh}
 
@@ -52,18 +49,17 @@ if [ "$ARCH" = "x86_64" ]; then
   LIBDIRSUFFIX="64"
 fi
 
-# Pre-download nwjs; cut down build time.
-# latest version has some issues; hardcoded version "0.77.0"
-NW_VER="0.77.0"
-NW_NAME=nwjs-v${NW_VER}-linux-x64
+# Pre-download electron zipped file AND source tar ball
+ELEC_VER="35.4.0"
+ELEC_NAME=electron-v${ELEC_VER}-linux-x64
 
 if [ ! -f $CWD/${PRGNAME}-${VERSION}.tar.gz ]; then
     echo "Missing source for $PRGNAME. Exiting"
     exit 1
 fi
 
-if [ ! -f $CWD/${NW_NAME}.tar.gz ]; then
-    echo "Missing source for nwJS tar ball. Exiting"
+if [ ! -f $CWD/${ELEC_NAME}.zip ]; then
+    echo "Missing source for zipped electron file. Exiting"
     exit 1
 fi
 
@@ -82,12 +78,14 @@ export PATH=$PG_PATH:$PATH
 set -e
 
 # Debugging shizz
-trap 'ERRCODE=$? && if [ ${ERRCODE} -ne 0 ]; then echo "The command \"${BASH_COMMAND}\" failed in \"${FUNCNAME}\" with exit code ${ERRCODE}."; fi' EXIT
+trap 'ERRCODE=$? && if [ ${ERRCODE} -ne 0 ]; then echo "The command \"${BASH_COMMAND}\" failed with exit code ${ERRCODE}."; fi' EXIT
 
 # STAGE is where we unpack sources
 STAGE=$TMP/stage-$PRGNAME
+
 SOURCEDIR=${STAGE}/${PRGNAME}-${VERSION}
-NW_DIR=${STAGE}/${NW_NAME}
+
+ELEC_DIR=${STAGE}/${ELEC_NAME}
 
 # make skelton directories for our package -- also /usr/doc/$PRGNAME-$VERSION
 BUILDROOT=$TMP/$PRGNAME
@@ -104,7 +102,11 @@ LIB_DIR=$BUILDROOT/usr/lib64/
 rm -rf ${STAGE} $BUILDROOT
 
 mkdir -p $TMP $OUTPUT ${STAGE} $BUILDROOT $PKGROOT \
-               $PKGBIN $PKGVENV $PKGWEB $PKGDOCS ${SYS_SHARE} ${LIB_DIR}
+               $PKGBIN $PKGVENV ${SYS_SHARE} ${LIB_DIR}
+
+# PKGWEB=$PKGROOT/web directory will be copied from source below!
+
+/usr/bin/corepack enable
 
 cd ${STAGE}
 
@@ -134,16 +136,16 @@ source $PKGVENV/bin/activate
 pip3 install --upgrade pip
 pip3 install wheel
 
-
 # Sphinx module is not included in Slackware, add to requirements.txt file;
 # needed to build docs, sphinxcontrib.youtube does not get installed?
 echo "" >> ${SOURCEDIR}/requirements.txt
-echo Sphinx >> ${SOURCEDIR}/requirements.txt
-echo sphinxcontrib.youtube >> ${SOURCEDIR}/requirements.txt
+echo "sphinx>=4.0,<6.0" >> ${SOURCEDIR}/requirements.txt
+echo "sphinxcontrib.youtube" >> ${SOURCEDIR}/requirements.txt
 
 # Install the requirements for venv
-# pip3 install --no-cache-dir --no-binary psycopg2 -r ${SOURCEDIR}/requirements.txt
-pip3 install --no-cache-dir --no-binary psycopg -r ${SOURCEDIR}/requirements.txt
+pip3 install --no-cache-dir --no-binary psycopg -r ${SOURCEDIR}/requirements.txt 2>&1 | tee pip-install.log
+
+# append to line above to create log: 2>&1 | tee pip-install.log
 
 VENVPATH="/opt/$PRGNAME/venv"
 
@@ -198,91 +200,44 @@ if test -d ${DIR_PYMODULES_PATH}; then
     ln -s $(basename ${DIR_PYMODULES_PATH}) ${DIR_PYMODULES_PATH}/../python
 fi
 
-# build runtime
+# Remove any TCL-related files that may cause us problems
+find "${PKGVENV}/" -name "_tkinter*" -print0 | xargs -0 rm -rf
+
+# Start build runtime
 
 cd ${STAGE}
 
-tar zxvf ${CWD}/${NW_NAME}.tar.gz
+unzip $CWD/${ELEC_NAME}.zip -d ${ELEC_NAME}
 
-# set sane permissions
-chown -R root:root $NW_DIR
+# Change the permission for others and group the same as the owner
+chmod -R og=u "${ELEC_NAME}"/*
 
-chmod -R 755 $NW_DIR
+# Explicitly remove write permissions for others and group
+chmod -R og-w "${ELEC_NAME}"/*
 
-# Copy nwjs into PKGBIN directory
-cp -r ${NW_DIR}/* ${PKGBIN}/
+cp -r ${ELEC_DIR}/* ${PKGBIN}/
 
-# rename nw to pgadmin4
-mv ${PKGBIN}/nw ${PKGBIN}/${PRGNAME}
+# rename electron to pgadmin4
+mv ${PKGBIN}/electron ${PKGBIN}/${PRGNAME}
 
-# copy from ${SOURCEDIR}/runtime : assets & src directories plus package.json file to PKGBIN
-cp -rp ${SOURCEDIR}/runtime/assets $PKGBIN
-cp -rp ${SOURCEDIR}/runtime/src $PKGBIN
-cp ${SOURCEDIR}/runtime/package.json $PKGBIN/.
+mkdir -p "${PKGBIN}/resources/app"
 
-# create links - few files get linked but those below.
-# another option is to add the nwjs library path to the system "ld path"
-# along with ldconfig. We keep the links for now.
+cp -r "${SOURCEDIR}/runtime/assets" "${PKGBIN}/resources/app/assets"
+cp -r "${SOURCEDIR}/runtime/src" "${PKGBIN}/resources/app/src"
 
-# make the link to installed files, not to those in build directory in /tmp
-# This should work.
-INSTAL_DIR=/opt/$PRGNAME
+cp "${SOURCEDIR}/runtime/package.json" "${PKGBIN}/resources/app"
+cp "${SOURCEDIR}/runtime/.yarnrc.yml" "${PKGBIN}/resources/app"
 
-ln -s $INSTAL_DIR/lib/libffmpeg.so $LIB_DIR
-ln -s $INSTAL_DIR/lib/libnode.so $LIB_DIR
-ln -s $INSTAL_DIR/lib/libnw.so $LIB_DIR
-ln -s $INSTAL_DIR/lib/libvk_swiftshader.so $LIB_DIR
-ln -s $INSTAL_DIR/lib/vk_swiftshader_icd.json $LIB_DIR
+# Install the runtime node_modules
 
-# build it
-# yarn cache clean & yarn --cwd $PKGBIN install --production=true
+cd "${PKGBIN}/resources/app"
+yarn set version berry
+yarn set version 3
+yarn plugin import workspace-tools
+yarn workspaces focus --production
 
-# yarn cache clean & yarn --cwd $PKGBIN install --verbose --production=true
-
-yarn --cwd $PKGBIN install --production=true
-
-# pgadmin4 desktop needs files and executables from ${SOURCEDIR}/web directory
-cp -r ${SOURCEDIR}/web/ $PKGROOT
-
-cd $PKGWEB
-
-yarn install
-yarn run bundle
-
-# remove not needed
-rm -f pgadmin4.db config_local.*
-rm -rf karma.conf.js package.json node_modules/ regression/ tools/ pgadmin/static/js/generated/.cache
-find . -name "tests" -type d -print0 | xargs -0 rm -rf
-find . -name "feature_tests" -type d -print0 | xargs -0 rm -rf
-find . -name "__pycache__" -type d -print0 | xargs -0 rm -rf
-
-# use just built PVE to build docs
-echo "Building the documentation..."
-
-mkdir -p ${PKGDOCS}/en_US/html
-cd "${SOURCEDIR}/docs/en_US"
-
-python3 build_code_snippet.py
-python3 ${PKGVENV}/bin/sphinx-build . "${PKGDOCS}/en_US/html"
-
-# Ensure our venv will use the correct Python interpretor, even if the
-# user has configured an alternative default.
-# DO THIS LAST!
-cd "${PKGVENV}/bin"
-PYTHON_INTERPRETER=$(/usr/bin/python3 -c "import os, sys; print(os.path.realpath(sys.executable))")
-rm python && ln -s python3 python
-rm python3 && ln -s "${PYTHON_INTERPRETER}" python3
-
-# needed config files
-install -Dm 644 /dev/stdin "$PKGWEB/config_distro.py" <<END
-SERVER_MODE = False
-HELP_PATH = "/opt/pgadmin4/docs/en_US/html"
-END
-cp $PKGWEB/config_distro.py $PKGWEB/config_local.py
-
-# Web setup script -- you are on your own for this
-mkdir -p ${PKGWEB}/usr/bin/
-cp ${SOURCEDIR}/pkg/linux/setup-web.sh ${PKGWEB}/usr/bin/
+# remove the yarn cache
+rm -rf .yarn .yarn*
 
 # Install icons
 install -Dm 644 ${SOURCEDIR}/pkg/linux/${PRGNAME}-16x16.png \
@@ -302,9 +257,69 @@ sed -i 's/Exec=\/usr\/pgadmin4\/bin\/pgadmin4/Exec=\/opt\/pgadmin4\/bin\/pgadmin
 install -Dm 644 "${SOURCEDIR}/pkg/linux/pgadmin4.desktop" \
                 "${SYS_SHARE}/applications/pgadmin4.desktop"
 
-# License files
+# End build runtime
+
+# use just built PVE to build docs
+echo "Building the documentation..."
+
+PKGDOCS=$PKGROOT/docs
+
+mkdir -p ${PKGDOCS}/en_US/html
+cd ${SOURCEDIR}/docs/en_US
+
+# Docs can be built in either ways below:
+
+# START docs build from pgadmin4 version 8.9 (2 lines total!)
+# python3 build_code_snippet.py
+# python3 ${PKGVENV}/bin/sphinx-build . "${PKGDOCS}/en_US/html"
+# END docs build from pgadmin4 version 8.9
+
+# START docs build from pgadmin4 version 9.4
+SYSTEM_PYTHON_PATH='/usr/bin/python3.9'
+python3 build_code_snippet.py
+SYS_PYTHONPATH=$("${SYSTEM_PYTHON_PATH}" -c "import sys; print(':'.join([p for p in sys.path if p]))")
+# shellcheck disable=SC2153
+PYTHONPATH=$PYTHONPATH:${SYS_PYTHONPATH} python3 -msphinx . "${PKGDOCS}/en_US/html"
+# END docs build from pgadmin4 version 9.4
+
+# Start copying
+cd "${SOURCEDIR}/web"
+
+yarn set version berry
+yarn set version 3
+yarn install
+yarn run bundle:dev
+# 2>&1 | tee yarn-run-bundle.log
+
+cp -r "${SOURCEDIR}/web" "${PKGROOT}/"
+
+cd "${PKGROOT}/web/"
+rm -f pgadmin4.db config_local.*
+rm -rf jest.config.js babel.* package.json .yarn* yarn* .editorconfig .eslint* node_modules/ regression/ tools/ pgadmin/static/js/generated/.cache
+find . -name "tests" -type d -print0 | xargs -0 rm -rf
+find . -name "feature_tests" -type d -print0 | xargs -0 rm -rf
+find . -name "__pycache__" -type d -print0 | xargs -0 rm -rf
+
+# needed config files
+install -Dm 644 /dev/stdin "${PKGROOT}/web/config_distro.py" <<END
+SERVER_MODE = False
+HELP_PATH = "/opt/pgadmin4/docs/en_US/html"
+END
+
+# Web setup script -- you are on your own for this
+mkdir -p ${PKGROOT}/web/usr/bin/
+cp ${SOURCEDIR}/pkg/linux/setup-web.sh ${PKGROOT}/web/usr/bin/
+
+# Ensure our venv will use the correct Python interpretor, even if the
+# user has configured an alternative default.
+# DO THIS LAST!
+cd "${PKGVENV}/bin"
+PYTHON_INTERPRETER=$(/usr/bin/python3 -c "import os, sys; print(os.path.realpath(sys.executable))")
+rm python && ln -s python3 python
+rm python3 && ln -s "${PYTHON_INTERPRETER}" python3
+
+# copy other files
 cp ${SOURCEDIR}/LICENSE $PKGROOT/
-cp ${SOURCEDIR}/DEPENDENCIES $PKGROOT/
 cp ${SOURCEDIR}/README.md $PKGROOT/
 
 # save our build scripts
