modified build script, use yarn to build runtime

diff --git a/pgadmin4-slackbuild/pgadmin4.SlackBuild b/pgadmin4-slackbuild/pgadmin4.SlackBuild
--- a/pgadmin4-slackbuild/pgadmin4.SlackBuild
+++ b/pgadmin4-slackbuild/pgadmin4.SlackBuild
@@ -1,5 +1,11 @@
 #!/bin/sh -e
 
+# Updated for pgAdmin4 version 5.0 on March 12/2021
+# Modified by: Wael Hammoudeh - w_hammoudeh at hotmail.com
+# 
+# Please DO read the two files: [ README and README.PVE ] included with
+# this script. W.H
+
 # Slackware build script for pgadmin4
 # Copyright 2019 Jeremy Hansen jebrhansen+SBo -at- gmail.com
 # All rights reserved.
@@ -21,36 +27,19 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Modified by: Wael Hammoudeh - w_hammoudeh at hotmail.com
-# Modification was inspired by the thread on Linux Questions Slackware forum
-# "https://www.linuxquestions.org/questions/slackware-14/"
-# with title: "building-pgadmin-4-in-slackware-current-4175648889"
-# 
-# Big thank you is due to "bassmadrigal" for his work posted in the above 
-# mentioned thread. Also thank you to ArchLinux PKGBUILD for pgAdmin4.
-# My approach was different; using Python Virtual Environment. Please DO read
-# the README.PVE file.
-# PVE is recommended by pgAdmin4 developers, we do not have to provide almost
-# 30 SlackBuilds scripts for required Python modules and PVE does not modify
-# system Python installation.
-#
-# This script REQUIRES Python Virtual Environment initialed at:
-# "/usr/local/pve/pgAdmin4-pve/".
-# Use the provided "mk-pve.sh" script to initial and setup your environment.
-# Full installation of slackware current is assumed, additionally slackware
-# package tools use is also assumed. 
-
-
 CWD=$(pwd)
-PRGNAM=pgadmin4
-VERSION=${VERSION:-4.30}
-BUILD=${BUILD:-1}
+PRG_NAME=pgadmin4
+VERSION=${VERSION:-5.0}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_wh}
-TMP=${TMP:-/tmp}
-PKG=$TMP/package-$PRGNAM
-OUTPUT=${OUTPUT:-/tmp}
-SRC=$TMP/$PRGNAM-$VERSION
 
+TMP=${TMP:-/tmp}
+BUILD_DIR=$TMP/WH
+PKG_DIR=$BUILD_DIR/package-$PRG_NAME
+SRC_DIR=$BUILD_DIR/$PRG_NAME-$VERSION
+OUTPUT=${OUTPUT:-/tmp}
+
+# call uname() to set ARCH
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
     i?86) ARCH=i586 ;;
@@ -59,21 +48,43 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
+LIBDIRSUFFIX=""
+if [ "$ARCH" = "x86_64" ]; then
   LIBDIRSUFFIX="64"
-else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
 fi
 
-# Step one: check for postgresql package installation - bailout if not found.
+PKG_ROOT=$PKG_DIR/usr/lib${LIBDIRSUFFIX}/$PRG_NAME-$VERSION
+
+# path to python virtual environment for version 5
+PVE_ROOT=/usr/local/pve
+APP_PVE=$PVE_ROOT/pgAdmin4-pve5
+
+if [ ! -f $APP_PVE/bin/activate ]; then
+  echo ""
+  echo "Missing or wrong path to application Python Virtual Environment!"
+  echo " This slackware build script requires Python Virtual Environment."
+  echo " Use the provided script \"mk-pve.sh\" found with this script to"
+  echo " initial PVE on your system, and please see the README.PVE file."
+  echo " You can run this script afterward."
+  echo " Exiting!"
+  echo ""
+  exit 1;
+fi
+
+source $APP_PVE/bin/activate
+
+# Save and check return value from above!
+RET_VALUE=$?
+SUCCESS=0
+
+if [ $RET_VALUE -ne $SUCCESS ]; then
+    echo "ERROR: Could not activate Python Virtual Environment!"
+    echo "Make sure to run mk-pve.sh script to set it up."
+    echo "Exiting"
+    exit 1
+fi
+
+# check for postgresql package installation - bailout if not found.
 # Assume slackpkg use. Is postgresql package installed?
 PG_PKG=$(ls /var/lib/pkgtools/packages/postgresql*)
 
@@ -106,42 +117,37 @@ if [ ! -f "$SLASH$PG_BIN_PART1" ]; then
 fi
 # seems good postgresql package installation.
 
-# Step 2: run the build in python virtual environment
-PVE_ROOT=/usr/local/pve
-APP_PVE=$PVE_ROOT/pgAdmin4-pve
+# check yarn
+if [ ! -x /usr/bin/yarn ]; then
 
-# activate python virtual environment
-if [ ! -f $APP_PVE/bin/activate ]; then
-  echo ""
-  echo "Missing or wrong path to application Python Virtual Environment!"
-  echo "This slackware build script requires Python Virtual Environment to be"
-  echo "initialed by \"mk-pve.sh\" found with build source."
-  echo "Please run the script \"mk-pve.sh\" before this one."
-  echo ""
-  exit 1;
-fi
-
-source $APP_PVE/bin/activate
-
-# Save and check return value from above!
-RET_VALUE=$?
-SUCCESS=0
-
-if [ $RET_VALUE -ne $SUCCESS ]; then
-    echo "ERROR: Could not activate Python Virtual Environment!"
-    echo "Make sure to run mk-pve.sh script to set it up."
-    echo "Exiting"
+    echo ""
+    echo "ERROR: missing yarn executable! pgAdmin4 version 5.0 requires yarn."
+    echo " Yarn build script is available from www.SlackBuilds.org, please"
+    echo " install yarn then run this script again ):"
+    echo ""
     exit 1
 fi
 
-rm -rf $PKG
-mkdir -p $TMP $PKG $OUTPUT
-cd $TMP
-rm -rf $PRGNAM-$VERSION
-tar xvzf $CWD/$PRGNAM-$VERSION.tar.gz
+# check nodeJS
+if [ ! -x /usr/bin/node ]; then
 
-# move to source root
-cd $SRC
+    echo ""
+    echo "ERROR: missing nodeJS executable! pgAdmin4 version 5.0 requires nodeJS 12+"
+    echo " nodejs build script is available from www.SlackBuilds.org, please"
+    echo " install nodejs then run this script again ):"
+    echo ""
+    exit 1
+fi
+
+mkdir -p $TMP $BUILD_DIR $PKG_DIR $PKG_ROOT $OUTPUT
+
+cd $BUILD_DIR
+
+rm -rf $SRC_DIR $PKG_ROOT/*/
+
+tar xvzf $CWD/$PRG_NAME-$VERSION.tar.gz
+
+cd $SRC_DIR
 
 # set sane permissions
 chown -R root:root .
@@ -150,124 +156,83 @@ find -L . \
   -o -perm 511 \) -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
-
-# use python virtual environment paths in runtime/Server.cpp
-patch -u runtime/Server.cpp -i $CWD/pve-paths.patch
-
-# use python virtual environment paths in runtime/ConfigWindow.ui
-# You NEED to manually enter PYTHONPATH on first use! Or use pgadmin4.conf 
-# found with build script by copying to ~/.config/pgadmin/pgadmin4.conf
-PYTHONVERSION="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
-sed -E "s|/usr/pgadmin4/web|/usr/lib${LIBDIRSUFFIX}/pgadmin4/web|g;
-        s|/usr/pgadmin4/lib/python[0-9\\.]+|/usr/local/pve/pgAdmin4-pve/lib${LIBDIRSUFFIX}/python${PYTHONVERSION}|g" \
-      -i runtime/ConfigWindow.ui
-
-convert +set date:create +set date:modify runtime/pgAdmin4.{ico,png}
-
-export PGADMIN_PYTHON_DIR=/usr
-
+  
+# yarn builds in runtime directory
 cd runtime
 
-# use qmake-qt5 - slackware current has qmake-qt4 AND qmake-qt5
-qmake-qt5
-make -j$(expr $(nproc) + 1)
+yarn install --verbose
 
-# make documentation
-cd $SRC
+# docs are built in source root AND need python packages from PVE
+
+cd $SRC_DIR
+
 make docs
 
-# Make javascripts bundles? Requires yarn v1.22.4 and nodejs v14.4.0
-if [ "${BUNDLE:-no}" = "yes" ]; then
-  echo ""
-  echo "Building javascripts bundles ..."
-  make install-node
-  make bundle
-  
-else
-  echo ""
-  echo "Skipping bundles making! Pass BUNDLE=yes to script to make them."
-  echo ""
-fi
+mkdir -p $PKG_ROOT/docs/en_US
 
-# done compiling ... copy files and directories to package
+cp -r $SRC_DIR/runtime $PKG_ROOT
+cp -r $SRC_DIR/web $PKG_ROOT
+cp -r $SRC_DIR/docs/en_US/_build/html $PKG_ROOT/docs/en_US
 
-# Install web and docs directories
-mkdir -p $PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/docs/en_US
-cp -a web "$PKG/usr/lib$LIBDIRSUFFIX/pgadmin4"
-cp -a docs/en_US/_build/html "$PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/docs/en_US"
+# some directories are not nedded anymore -- remove them
+# remove not needed
+rm -rf $PKG_ROOT/web/regression
+rm -rf "$PKG_ROOT/docs/en_US/html/_sources"
 
-# file provided with this slackbuild "pgAdmin4-pve.sh" is a simple wrapper
-# script to start pgAdimin4 executable in python virtual environment
-start_script=pgAdmin4-pve.sh
+# remove __pycache__ and test(s) directories
+find $PKG_ROOT/web -name "__pycache__" -type d -print0 | xargs -0 rm -rf
+find $PKG_ROOT/web -name "tests" -type d -print0 | xargs -0 rm -rf
+find $PKG_ROOT/web -name "feature_tests" -type d -print0 | xargs -0 rm -rf
 
-# Install binary and scripts 
-install -Dm 755 runtime/pgAdmin4 "$PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/runtime/pgAdmin4"
-install -Dm 755 $CWD/$start_script "$PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/runtime/$start_script"
-install -Dm 755 /dev/stdin "$PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/runtime/pgadmin4-initial-server" <<END
-#!/bin/sh
-# run script once to initial server in desktop mode
-source $APP_PVE/bin/activate
-python3 /usr/lib$LIBDIRSUFFIX/pgadmin4/web/setup.py
+# needed config files
+install -Dm 644 /dev/stdin "$PKG_ROOT/web/config_distro.py" <<END
+SERVER_MODE = False
+HELP_PATH = "/usr/lib$LIBDIRSUFFIX/$PRG_NAME-$VERSION/docs/en_US/html"
+END
+cp $PKG_ROOT/web/config_distro.py $PKG_ROOT/web/config_local.py
+
+# we need to set paths in dev_config.json file
+install -Dm 644 /dev/stdin "$PKG_ROOT/runtime/dev_config.json" <<END
+{
+    "pythonPath": "$APP_PVE/bin/python3",
+    "pgadminFile": "/usr/lib$LIBDIRSUFFIX/$PRG_NAME-$VERSION/web/pgAdmin4.py"
+}
 END
 
 # Install icons
-install -Dm 644 runtime/pgAdmin4-0.png "$PKG/usr/share/icons/hicolor/256x256/apps/pgAdmin4.png"
-install -Dm 644 runtime/pgAdmin4-1.png "$PKG/usr/share/icons/hicolor/48x48/apps/pgAdmin4.png"
-install -Dm 644 runtime/pgAdmin4-2.png "$PKG/usr/share/icons/hicolor/32x32/apps/pgAdmin4.png"
-install -Dm 644 runtime/pgAdmin4-3.png "$PKG/usr/share/icons/hicolor/16x16/apps/pgAdmin4.png"
+install -Dm 644 $SRC_DIR/pkg/linux/$PRG_NAME-16x16.png \
+                "$PKG_DIR/usr/share/icons/hicolor/16x16/apps/$PRG_NAME.png"
+install -Dm 644 $SRC_DIR/pkg/linux/$PRG_NAME-32x32.png \
+                "$PKG_DIR/usr/share/icons/hicolor/32x32/apps/$PRG_NAME.png"
+install -Dm 644 $SRC_DIR/pkg/linux/$PRG_NAME-48x48.png \
+                "$PKG_DIR/usr/share/icons/hicolor/48x48/apps/$PRG_NAME.png"
+install -Dm 644 $SRC_DIR/pkg/linux/$PRG_NAME-64x64.png \
+                "$PKG_DIR/usr/share/icons/hicolor/64x64/apps/$PRG_NAME.png"
+install -Dm 644 $SRC_DIR/pkg/linux/$PRG_NAME-128x128.png \
+                "$PKG_DIR/usr/share/icons/hicolor/128x128/apps/$PRG_NAME.png"
 
-# needed config files
-install -Dm 644 /dev/stdin "$PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/web/config_distro.py" <<END
-SERVER_MODE = False
-HELP_PATH = "/usr/lib$LIBDIRSUFFIX/pgadmin4/docs/en_US/html"
-END
-cp $PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/web/config_distro.py \
-   $PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/web/config_local.py
+# install our script to start application
+START_SCRIPT=pgAdmin4-pve.sh
+install -Dm 755 $CWD/$START_SCRIPT $PKG_ROOT/runtime/$START_SCRIPT
 
-# remove not needed
-rm -rf $PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/web/regression
-rm -rf "$PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/docs/en_US/html/_sources"
+# use our start script in desktop file
+sed -E "s|Exec=/usr/pgadmin4/bin/pgadmin4|Exec=/usr/lib$LIBDIRSUFFIX/$PRG_NAME-$VERSION/runtime/$START_SCRIPT|" \
+       -i $SRC_DIR/pkg/linux/pgadmin4.desktop
 
-# remove __pycache__ and test(s) directories
-find $PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/web -name "__pycache__" -type d -print0 | xargs -0 rm -rf
-find $PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/web -name "test" -type d -print0 | xargs -0 rm -rf
-find $PKG/usr/lib$LIBDIRSUFFIX/pgadmin4/web -name "tests" -type d -print0 | xargs -0 rm -rf
+install -Dm 644 $SRC_DIR/pkg/linux/pgadmin4.desktop "$PKG_DIR/usr/share/applications/pgAdmin4.desktop"
 
-# Install desktop file
-# Note we use our start_script to start the application
-install -Dm 755 /dev/stdin "$PKG/usr/share/applications/pgAdmin4.desktop" <<END
-[Desktop Entry]
-Encoding=UTF-8
-Name=pgAdmin 4
-Exec=/usr/lib$LIBDIRSUFFIX/pgadmin4/runtime/$start_script
-Icon=pgAdmin4
-Type=Application
-Categories=Application;Development;Database;
-MimeType=text/html
-DocPath=/usr/lib$LIBDIRSUFFIX/pgadmin4/docs/en_US/html
-Comment=PostgreSQL Tools
-Keywords=database;db;sql;query;administration;development;
-END
+# save our build scripts
+mkdir -p $PKG_DIR/usr/doc/$PRG_NAME-$VERSION
+cp $CWD/LICENSE $PKG_DIR/usr/doc/$PRG_NAME-$VERSION/
+cp $CWD/README $PKG_DIR/usr/doc/$PRG_NAME-$VERSION/
+cp $CWD/README.PVE $PKG_DIR/usr/doc/$PRG_NAME-$VERSION/
+cp $CWD/$PRG_NAME.SlackBuild $PKG_DIR/usr/doc/$PRG_NAME-$VERSION/
+cp $CWD/pgAdmin4-pve.sh $PKG_DIR/usr/doc/$PRG_NAME-$VERSION/
+cp $CWD/mk-pve.sh $PKG_DIR/usr/doc/$PRG_NAME-$VERSION/
 
-# I do copy ALL package-making files
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp $CWD/LICENSE $PKG/usr/doc/$PRGNAM-$VERSION/
-cp $CWD/README $PKG/usr/doc/$PRGNAM-$VERSION/
-cp $CWD/README.PVE $PKG/usr/doc/$PRGNAM-$VERSION/
-cp $CWD/$PRGNAM.SlackBuild $PKG/usr/doc/$PRGNAM-$VERSION/
-cp $CWD/pgAdmin4-pve.sh $PKG/usr/doc/$PRGNAM-$VERSION/
-cp $CWD/mk-pve.sh $PKG/usr/doc/$PRGNAM-$VERSION/
-cp $CWD/pve-paths.patch $PKG/usr/doc/$PRGNAM-$VERSION/
-cp $CWD/pgadmin4.conf $PKG/usr/doc/$PRGNAM-$VERSION
+# copy package description
+mkdir -p $PKG_DIR/install
+cat $CWD/slack-desc > $PKG_DIR/install/slack-desc
 
-mkdir -p $PKG/install
-cat $CWD/slack-desc > $PKG/install/slack-desc
-
-cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
-
-# be nice
-deactivate
-cd $CWD
-
-exit $SUCCESS
+cd $PKG_DIR
+/sbin/makepkg -l y -c n $OUTPUT/$PRG_NAME-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
