upgrade to version 6.1 plus major script rewrite

diff --git a/pgadmin4-slackbuild/pgadmin4.SlackBuild b/pgadmin4-slackbuild/pgadmin4.SlackBuild
--- a/pgadmin4-slackbuild/pgadmin4.SlackBuild
+++ b/pgadmin4-slackbuild/pgadmin4.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-# Updated for pgAdmin4 version 6.0
-# Date: October 16/2021
+# Updated for pgAdmin4 version 6.1
+# Date: October 22/2021
 
 # Slackware build script for pgadmin4
 # Copyright 2019 Jeremy Hansen jebrhansen+SBo -at- gmail.com
@@ -26,10 +26,9 @@
 
 # Modified by: Wael Hammoudeh - w_hammoudeh at hotmail.com
 
-
 CWD=$(pwd)
 PRGNAME=pgadmin4
-VERSION=6.0
+VERSION="6.1"
 BUILD=${BUILD:-1}
 TAG=${TAG:-_wh}
 
@@ -50,80 +49,29 @@ if [ "$ARCH" = "x86_64" ]; then
   LIBDIRSUFFIX="64"
 fi
 
+# we use two source files; do we have both?
+NW_VER="0.55.0"
+
+if [ ! -f $CWD/${PRGNAME}-${VERSION}.tar.gz ]; then
+    echo "Missing source for $PRGNAME. Exiting"
+    exit 1
+fi
+
+if [ ! -f $CWD/nwjs-v${NW_VER}-linux-x64.tar.gz ]; then
+    echo "Missing source for nwJS tar ball. Exiting"
+    exit 1
+fi
+
 # we need postgresql bin directory in our path
-# check for postgresql package installation - bailout if not found.
-# Assume slackpkg use. Is postgresql package installed?
-PG_PKG=$(ls /var/lib/pkgtools/packages/postgresql*)
+PG_PATH=`/usr/bin/pg_config --bindir`
 
-# empty string from ls command above indicates missing PostgreSQL package
-if [ -z "$PG_PKG" ]; then
-    echo "PostgreSQL package not found. Please install PostgreSQL with"
-    echo "slackware package tools. Exiting!"
-    exit 1;
-fi
-
-# pg_config file is usually installed in postgresql bin directory
-PG_BIN_PART1=$(cat $PG_PKG | egrep "*/bin/pg_config")
-
-# empty string means missed up installation!
-if [ -z "$PG_BIN_PART1" ]; then
-    echo "ERROR: Could not get path for PostgreSQL bin directory."
-    echo "Please make sure that PostgreSQL package is installed in"
-    echo "your system with slackware package tools"
-    echo "Exiting!"
-    exit 1;
-fi
-
-# prepend leading slash to directory
-PG_CONFIG=/$PG_BIN_PART1
-
-# with leading slash this is pg_config file which MUST exist in file system
-if [ ! -f "$PG_CONFIG" ]; then
-    echo "ERROR: Could not find postgresql pg_config configuration file."
-    echo "Ensure that postgresql package is properly installed with slackware"
-    echo "package tools. Exiting."
+if [ -z "$PG_PATH" ]; then
+    echo "Could not get postgresql binary directory from pg_config."
+    echo "Is postgresql package installed? Exiting."
     exit 1
 fi
 
-# seems good postgresql package installation. Make sure we get the right libpq
-PG_PATH=`dirname $PG_CONFIG`
 export PATH=$PG_PATH:$PATH
-
-# check yarn installation
-if [ ! -x /usr/bin/yarn ]; then
-
-    echo ""
-    echo "ERROR: missing yarn executable! pgAdmin4 version 6.0 requires yarn."
-    echo " Yarn build script is available from www.SlackBuilds.org, please"
-    echo " install yarn then run this script again ):"
-    echo ""
-    exit 1
-fi
-
-# check nodeJS
-if [ ! -x /usr/bin/node ]; then
-
-    echo ""
-    echo "ERROR: missing nodeJS executable! pgAdmin4 version 6.0 requires nodeJS 12+"
-    echo " nodejs build script is available from www.SlackBuilds.org, please"
-    echo " install nodejs then run this script again ):"
-    echo ""
-    exit 1
-
-fi
-
-# check nodeJS version, must be > 12
-VERSTR=`node --version`
-VERNUM=`echo $VERSTR | cut -c 1 --complement`
-MAJOR=`echo $VERNUM | cut -d "." -f 1`
-
-if [ $MAJOR -lt 12 ]; then
-    echo " ERROR: wrong nodeJS version, less than 12. pgAdmin4 requires nodeJS 12+"
-    echo " nodejs build script is available from www.SlackBuilds.org, please"
-    echo " install nodejs then run this script again ):"
-    echo ""
-    exit 1
-fi
 
 # exit on error
 set -e
@@ -131,21 +79,25 @@ set -e
 # Debugging shizz
 trap 'ERRCODE=$? && if [ ${ERRCODE} -ne 0 ]; then echo "The command \"${BASH_COMMAND}\" failed in \"${FUNCNAME}\" with exit code ${ERRCODE}."; fi' EXIT
 
-# make skelton directories for our package
-BUILDROOT=${TMP}/${PRGNAME}
-DESKTOPROOT=${BUILDROOT}/desktop
-METAROOT=${BUILDROOT}/meta
-SERVERROOT=${BUILDROOT}/server
-WEBROOT=${BUILDROOT}/web
-
 SOURCEDIR=${CWD}/${PRGNAME}-${VERSION}
+
+# make skelton directories for our package -- also /usr/doc/$PRGNAME-$VERSION
+BUILDROOT=${TMP}/${PRGNAME}
+PKGROOT=${BUILDROOT}/opt/${PRGNAME}
+PKGBIN=${PKGROOT}/bin
+PKGVENV=${PKGROOT}/venv
+PKGWEB=${PKGROOT}/web
+PKGDOCS=${PKGROOT}/docs
+SYS_SHARE=${BUILDROOT}/usr/share
 
 # start with empty directories
 rm -rf ${SOURCEDIR} ${BUILDROOT}
 
-mkdir -p $TMP $OUTPUT $BUILDROOT $DESKTOPROOT $METAROOT $SERVERROOT $WEBROOT
+mkdir -p $TMP $OUTPUT $BUILDROOT $PKGROOT $PKGBIN $PKGVENV $PKGWEB $PKGDOCS $SYS_SHARE
 
 tar xvzf $CWD/$PRGNAME-$VERSION.tar.gz
+
+cd $SOURCEDIR
 
 # set sane permissions
 chown -R root:root ${SOURCEDIR}
@@ -155,51 +107,177 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-# patch _build_runtime() function to use pre-downloaded tar ball
-patch ${SOURCEDIR}/pkg/linux/build-functions.sh $CWD/nwjs-download.diff
+# see $SOURCEDIR/pkg/linux/build-functions.sh file
 
-# we use some functions provided by pgAdmin4 developers to build the package
-source ${SOURCEDIR}/pkg/linux/build-functions.sh
+echo "Creating the virtual environment..."
 
-# APP_NAME varaiable needed by _create_python_virtualenv() function
-APP_NAME=${PRGNAME}
+cd ${PKGROOT}
 
-_create_python_virtualenv "slackware"
+# Create the blank venv -- in our PKGVENV directory
+python3 -m venv ${PKGVENV}
+source ${PKGVENV}/bin/activate
 
-_build_runtime
+# Make sure we have the wheel package present, as well as the latest pip
+pip3 install --upgrade pip
+pip3 install wheel
 
-# build temporary PVE to make docs
-$CWD/mk-doc-pve.sh $TMP
+# Sphinx module is not included in Slackware, add it to requirements.txt file;
+# needed to build docs
+echo Sphinx >> ${SOURCEDIR}/requirements.txt
 
-DOC_PVE=$TMP/docpve
-source $DOC_PVE/bin/activate
+# Install the requirements for venv
+pip3 install --no-cache-dir --no-binary psycopg2 -r ${SOURCEDIR}/requirements.txt
+#pip3 install --no-binary psycopg2 -r ${SOURCEDIR}/requirements.txt
 
-_build_docs "slackware"
+REALVENVPATH="/opt/${PRGNAME}/venv"
 
-deactivate
+# Fixup the paths in the venv activation scripts -- note double quets
+sed -i "s|VIRTUAL_ENV=.*|VIRTUAL_ENV=\"${REALVENVPATH}\"|g" venv/bin/activate
+sed -i "s|setenv VIRTUAL_ENV .*|setenv VIRTUAL_ENV \"${REALVENVPATH}\"|g" venv/bin/activate.csh
+sed -i "s|set -gx VIRTUAL_ENV .*|set -gx VIRTUAL_ENV \"${REALVENVPATH}\"|g" venv/bin/activate.fish
 
-# done with temporary PVE, so we remove it
-rm -rf $DOC_PVE
+rm -rf ${PKGVENV}/bin/__pycache__
 
-_copy_code
+# Fixup hash bangs
+sed -i 's/#!.*\/python3/#\!\/opt\/pgadmin4\/venv\/bin\/python3/g' venv/bin/*
 
-cp -r $SERVERROOT/usr/pgadmin4/ $DESKTOPROOT/usr/
+# Figure out some paths for use when completing the venv
+# Use "python3" here as we want the venv path
+PYMODULES_PATH=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
+DIR_PYMODULES_PATH=`dirname ${PYMODULES_PATH}`
+
+# Use /usr/bin/python3 here as we want the system path
+PYSYSLIB_PATH=$(/usr/bin/python3 -c "import sys; print('%s/lib64/python%d.%.d' % (sys.prefix, sys.version_info.major, sys.version_info.minor))")
+
+# Symlink in the rest of the Python libs. This is required because the runtime
+# will clear PYTHONHOME for safety, which has the side-effect of preventing
+# it from finding modules that are not explicitly included in the venv
+cd ${DIR_PYMODULES_PATH}
+
+# Files
+for FULLPATH in ${PYSYSLIB_PATH}/*.py; do
+    FILE=${FULLPATH##*/}
+    if [ ! -e ${FILE} ]; then
+        ln -s ${FULLPATH} ${FILE}
+    fi
+done
+
+# Paths
+for FULLPATH in ${PYSYSLIB_PATH}/*/; do
+    FULLPATH=${FULLPATH%*/}
+    FILE=${FULLPATH##*/}
+    if [ ! -e ${FILE} ]; then
+        ln -s ${FULLPATH} ${FILE}
+    fi
+done
+
+# Remove tests
+cd site-packages
+find . -name "test" -type d -print0 | xargs -0 rm -rf
+find . -name "tests" -type d -print0 | xargs -0 rm -rf
+
+# Link the python<version> directory to python so that the private environment path is found by the application.
+if test -d ${DIR_PYMODULES_PATH}; then
+    ln -s $(basename ${DIR_PYMODULES_PATH}) ${DIR_PYMODULES_PATH}/../python
+fi
+
+# build runtime
+
+tar zxvf ${CWD}/nwjs-v${NW_VER}-linux-x64.tar.gz
+
+# Copy nwjs into PKGBIN directory
+cp -r ${CWD}/nwjs-v${NW_VER}-linux-x64/* ${PKGBIN}/
+
+# rename nw to pgadmin4
+mv ${PKGBIN}/nw ${PKGBIN}/${PRGNAME}
+
+# copy from ${SOURCEDIR}/runtime the assets & src directories plus package.json file to PKGBIN
+cp -rp ${SOURCEDIR}/runtime/assets ${PKGBIN}
+cp -rp ${SOURCEDIR}/runtime/src ${PKGBIN}
+cp ${SOURCEDIR}/runtime/package.json ${PKGBIN}/.
+
+yarn --cwd ${PKGBIN} install --production=true
+
+# pgadmin4 desktop needs files and executables from $SOURCEDIR/web directory
+cp -r ${SOURCEDIR}/web/ ${PKGROOT}
+
+cd ${PKGWEB}
+
+yarn install
+yarn run bundle
+
+# remove not needed
+rm -f pgadmin4.db config_local.*
+rm -rf karma.conf.js package.json node_modules/ regression/ tools/ pgadmin/static/js/generated/.cache
+find . -name "tests" -type d -print0 | xargs -0 rm -rf
+find . -name "feature_tests" -type d -print0 | xargs -0 rm -rf
+find . -name "__pycache__" -type d -print0 | xargs -0 rm -rf
+
+# use just built PVE to build docs
+echo "Building the documentation..."
+
+mkdir -p ${PKGDOCS}/en_US/html
+cd "${SOURCEDIR}/docs/en_US"
+
+python3 build_code_snippet.py
+python3 ${PKGVENV}/bin/sphinx-build . "${PKGDOCS}/en_US/html"
+
+# Ensure our venv will use the correct Python interpretor, even if the
+# user has configured an alternative default.
+# DO THIS LAST!
+cd "${PKGVENV}/bin"
+PYTHON_INTERPRETER=$(/usr/bin/python3 -c "import os, sys; print(os.path.realpath(sys.executable))")
+rm python && ln -s python3 python
+rm python3 && ln -s "${PYTHON_INTERPRETER}" python3
+# TODO :: is the above correct? I think ......????
+
+# needed config files
+install -Dm 644 /dev/stdin "$PKGWEB/config_distro.py" <<END
+SERVER_MODE = False
+HELP_PATH = "/opt/pgadmin4/docs/en_US/html"
+END
+cp $PKGWEB/config_distro.py $PKGWEB/config_local.py
+
+# Web setup script -- you are on your own for this
+mkdir -p ${PKGWEB}/usr/bin/
+cp ${SOURCEDIR}/pkg/linux/setup-web.sh ${PKGWEB}/usr/bin/
+
+# Install icons
+install -Dm 644 ${SOURCEDIR}/pkg/linux/${PRGNAME}-16x16.png \
+                "$SYS_SHARE/icons/hicolor/16x16/apps/${PRGNAME}.png"
+install -Dm 644 ${SOURCEDIR}/pkg/linux/${PRGNAME}-32x32.png \
+                "$SYS_SHARE/icons/hicolor/32x32/apps/${PRGNAME}.png"
+install -Dm 644 ${SOURCEDIR}/pkg/linux/${PRGNAME}-48x48.png \
+                "$SYS_SHARE/icons/hicolor/48x48/apps/${PRGNAME}.png"
+install -Dm 644 ${SOURCEDIR}/pkg/linux/${PRGNAME}-64x64.png \
+                "$SYS_SHARE/icons/hicolor/64x64/apps/${PRGNAME}.png"
+install -Dm 644 ${SOURCEDIR}/pkg/linux/${PRGNAME}-128x128.png \
+                "$SYS_SHARE/icons/hicolor/128x128/apps/${PRGNAME}.png"
+
+# fix path in desktop file
+sed -i 's/Exec=\/usr\/pgadmin4\/bin\/pgadmin4/Exec=\/opt\/pgadmin4\/bin\/pgadmin4/' \
+           ${SOURCEDIR}/pkg/linux/pgadmin4.desktop
+install -Dm 644 "${SOURCEDIR}/pkg/linux/pgadmin4.desktop" \
+                "${SYS_SHARE}/applications/pgadmin4.desktop"
+
+# License files
+cp "${SOURCEDIR}/LICENSE" "${PKGROOT}/"
+cp "${SOURCEDIR}/DEPENDENCIES" "${PKGROOT}/"
+cp "${SOURCEDIR}/README.md" "${PKGROOT}/"
 
 # save our build scripts
-mkdir -p $DESKTOPROOT/usr/doc/$PRGNAME-$VERSION
-cp $CWD/LICENSE $DESKTOPROOT/usr/doc/$PRGNAME-$VERSION/
-cp $CWD/README $DESKTOPROOT/usr/doc/$PRGNAME-$VERSION/
-cp $CWD/nwjs-download.diff $DESKTOPROOT/usr/doc/$PRGNAME-$VERSION/
-cp $CWD/$PRGNAME.SlackBuild $DESKTOPROOT/usr/doc/$PRGNAME-$VERSION/
-cp $CWD/mk-doc-pve.sh $DESKTOPROOT/usr/doc/$PRGNAME-$VERSION/
-cp $CWD/$PRGNAME.info $DESKTOPROOT/usr/doc/$PRGNAME-$VERSION/
+MYDOC=$BUILDROOT/usr/doc/$PRGNAME-$VERSION
+mkdir -p $MYDOC
+cp $CWD/LICENSE $MYDOC/
+cp $CWD/README $MYDOC/
+cp $CWD/$PRGNAME.SlackBuild $MYDOC/
+cp $CWD/$PRGNAME.info $MYDOC/
+cp $CWD/slack-desc $MYDOC/
 
-# copy package description
-mkdir -p $DESKTOPROOT/install
-cat $CWD/slack-desc > $DESKTOPROOT/install/slack-desc
+mkdir -p $BUILDROOT/install
+cat $CWD/slack-desc > $BUILDROOT/install/slack-desc
 
-cd $DESKTOPROOT
-
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAME-$VERSION-$ARCH-$BUILD$TAG.tgz
+cd $BUILDROOT
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAME-$VERSION-$ARCH-$BUILD$TAG.txz
 
 exit 0
